# Site settings
title: Getting With The Program
header-img: img/home-bg.png
email: ericaplofsky@gmail.com
copyright_name: eplof44
description: > # this means to ignore newlines until "baseurl:"
  Bringing you an [array] of insight along my coding journey.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  eplof44
learn_profile: eplof44
email_username: ericaplofsky@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
